### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by imcute-aaaa** [KihtrakRaknas/cloud_variable#1]
https://snap.berkeley.edu/snap/snap.html#present:Username=18001767679&ProjectName=cloud%20demo%20woo does not multiplayer at all
idk how this is broken

**Comment by imcute-aaaa** [comment]
It does not break on https://snap.berkeley.edu/snap/snap.html#present:Username=18001767679&ProjectName=cloud%20chatties

**Comment by KihtrakRaknas** [comment]
It looks like this issue is with an unrelated project. You can find information on this project does at: [https://kihtrak.com/cloud_variable/](https://kihtrak.com/cloud_variable/)

**Comment by imcute-aaaa** [comment]
nah this thingy relates with the project you mentioned cuz a js function block

**Comment by imcute-aaaa** [comment]
also percent 60 of ur cloud vars are snap
snap does not have internal cloud vars and we had to implement them in some way

**Comment by KihtrakRaknas** [comment]
I am not familiar with this site but taking a glance at the links you sent. It looks like in the broken project you are not using the custom get and set blocks and are instead using "script variables". Maybe that is related to your issue.
What do you mean by `also percent 60 of ur cloud vars are snap`?
Also, where did you get the idea to use cloud_variables with snap! I think the use case is really cool!

**Comment by imcute-aaaa** [comment]
Script varables mean local variable declaring.It has nothing to do with errors.
The majority of your cloud vars are from people I know and are from the snap forum.
Snap does not have cloud variables.

**Comment by KihtrakRaknas** [comment]
I don't know what your project was trying to do. Maybe try to reproduce your issue with a less complex project?
On an unrelated note, looking at your project I would advise using the script linked to on the project page. The client side code for cloud_variables has changed and it looks like your project is still using the old one.

**Comment by imcute-aaaa** [comment]
Sorry,just found out that its my problem,forgot to add player object

**Comment by imcute-aaaa** [comment]
Oh,and I was wrong about your cloud variable usage distribution.Just found out "Cloud variables are seperated by origin. This means that each domain/subdomain shares all their cloud variables. This enables different subpages on your site to talk to each other."

**Comment by KihtrakRaknas** [comment]
Glad to hear you fixed the problem!
